package com.qubit.terra.qubAccessControl.domain;

public enum AccessControlAuditLogType {
    PERMISSION_ADDED, PERMISSION_REMOVED, MEMBER_ADDED, MEMBER_REMOVED, OBJECT_ADDED, OBJECT_REMOVED, CHILD_PROFILE_ADDED,
    CHILD_PROFILE_REMOVED, PARENT_PROFILE_ADDED, PARENT_PROFILE_REMOVED;
}
